// itemsData.js

export const headers = [
  "id",
  "Title",
  "Category",
  "Group",
  "Form",
  "Department",
  "Count",
  "Size",
  "Price Per Unit",
  "Price",
];

export const itemsData = [
  [
    1,
    "Bays Original Pre-sliced English Muffins",
    "english muffins",
    "Grains",
    "sliced",
    "baked goods",
    6,
    "12 oz",
    "29¢/oz",
    3.48,
  ],
  [
    2,
    "La Banderita Ricas Flour Tortillas, Regular, Family Pack, 20 count, 22.5 oz",
    "flour tortillas",
    "Grains",
    "block",
    "baked goods",
    20,
    "22.5 oz",
    "14.4¢/oz",
    3.24,
  ],
  [
    3,
    "Mission Super Soft Soft Taco Flour Tortillas, 17.5 oz, 10 Count",
    "flour tortillas",
    "Grains",
    "block",
    "baked goods",
    10,
    "17.5 oz",
    "15.9¢/oz",
    2.78,
  ],
  [
    4,
    "Great Value Honey Wheat Bread, 20 oz",
    "bread",
    "Grains",
    "loaf",
    "baked goods",
    "",
    "20 oz",
    "9.4¢/oz",
    1.87,
  ],
  [
    5,
    "Lender’s Refrigerated Pre-Sliced Plain Bagel, 6 per Bag, 17.1 oz Bag",
    "bagels",
    "Grains",
    "sliced",
    "baked goods",
    6,
    "17.1 oz",
    "16¢/oz",
    2.74,
  ],
  [
    6,
    "Great Value Pure Granulated Sugar, 10lb",
    "sugar",
    "Others",
    "granulated",
    "pantry",
    "",
    "10 lb",
    "5.1¢/oz",
    8.17,
  ],
  [
    7,
    "Great Value Milk Chocolate Chips, 11.5 oz",
    "chocolate chips",
    "Others",
    "bag",
    "baking",
    "",
    "11.5 oz",
    "20.2¢/oz",
    2.32,
  ],
  [
    8,
    "V8 Strawberry Banana 100% Fruit and Vegetable Juice, 46 fl oz Bottle",
    "fruit juice",
    "Frutes/Vege.",
    "bottle",
    "beverages",
    "",
    "46 fl oz",
    "7.7¢/fl oz",
    3.54,
  ],
  [
    9,
    "Tropicana Pure Premium Low Acid No Pulp Orange Fruit Juice, 52 fl oz, Bottle",
    "fruit juice",
    "Frutes/Vege.",
    "bottle",
    "beverages",
    "",
    "52 fl oz",
    "7.6¢/fl oz",
    3.94,
  ],
  [
    10,
    "Malt-O-Meal Cinnamon Toasters Breakfast Cereal, Cinnamon Cereal Squares, 33 oz Resealable Bag",
    "cereal",
    "Grains",
    "box",
    "breakfast",
    "",
    "33 oz",
    "16.6¢/oz",
    5.48,
  ],
  [
    11,
    "Great Value 100% Whole Grain Old Fashioned Oats, 42 oz",
    "oats",
    "Grains",
    "bag",
    "breakfast",
    "",
    "42 oz",
    "9.5¢/oz",
    3.98,
  ],
  [
    12,
    "Malt O Meal Quick Cooking Hot Wheat Cereal, Original, 36 oz Box",
    "cereal",
    "Grains",
    "box",
    "breakfast",
    "",
    "36 oz",
    "13.8¢/oz",
    4.96,
  ],
  [
    13,
    "Great Value French Vanilla Coffee Creamer, 64 fl oz",
    "coffee creamer",
    "Dairy",
    "bottle",
    "beverages",
    "",
    "64 fl oz",
    "7.8¢/fl oz",
    4.98,
  ],
  [
    14,
    "Folgers Black Silk Ground Coffee, Smooth Dark Roast Coffee, 33.7 Ounce Canister",
    "coffee",
    "Others",
    "canister",
    "beverages",
    "",
    "33.7 oz",
    "42.8¢/oz",
    14.44,
  ],
  [
    15,
    "Florida Crystals Organic Raw Cane Sugar, 6 lb Pouch",
    "sugar",
    "Others",
    "cane",
    "pantry",
    "",
    "6 lb",
    "28.6¢/oz",
    10.17,
  ],
  [
    16,
    "Great Value Deli Style Sliced Non-Smoked Provolone Cheese, 8 oz, 12 Count",
    "cheese",
    "Dairy",
    "sliced",
    "dairy",
    12,
    "8 oz",
    "24.6¢/oz",
    1.97,
  ],
  [
    17,
    "Great Value Chive & Onion Cream Cheese Spread, 8 oz Tub",
    "cream cheese",
    "Dairy",
    "tub",
    "dairy",
    "",
    "8 oz",
    "26.5¢/oz",
    2.12,
  ],
  [
    18,
    "Daisy Pure and Natural Cottage Cheese, 4% Milkfat, 16 oz (1 lb) Tub (Refrigerated)",
    "cottage cheese",
    "Dairy",
    "tub",
    "dairy",
    "",
    "16 oz",
    "18¢/oz",
    2.88,
  ],
  [
    19,
    "Great Value Cream Cheese Brick, 8 oz (Refrigerated)",
    "cream cheese",
    "Dairy",
    "brick",
    "dairy",
    "",
    "8 oz",
    "23.3¢/oz",
    1.86,
  ],
  [
    20,
    "Pillsbury Flaky Layers Refrigerated Buttermilk Biscuits, 5 ct., 6 oz.",
    "biscuits",
    "Grains",
    "package",
    "baked goods",
    5,
    "6 oz",
    "25.7¢/oz",
    1.54,
  ],
  [
    21,
    "Great Value Cream Cheese 8 oz, 2 Count",
    "cream cheese",
    "Dairy",
    "package",
    "dairy",
    2,
    "8 oz",
    "21.5¢/oz",
    3.44,
  ],
  [
    22,
    "Great Value Large White Eggs, 18 Count",
    "eggs",
    "Dairy",
    "carton",
    "dairy",
    18,
    "",
    "",
    3.96,
  ],
  [
    23,
    "Daisy Pure and Natural Sour Cream, 16 oz (1 lb) Tub (Refrigerated)",
    "sour cream",
    "Dairy",
    "tub",
    "dairy",
    "",
    "16 oz",
    "15.5¢/oz",
    2.48,
  ],
  [
    24,
    "Great Value Mild Cheddar Cheese, 32 oz",
    "cheese",
    "Dairy",
    "block",
    "dairy",
    "",
    "32 oz",
    "19.8¢/oz",
    6.34,
  ],
  [
    25,
    "Great Value Half and Half, 64 fl oz",
    "half and half",
    "Dairy",
    "bottle",
    "dairy",
    "",
    "64 fl oz",
    "8.8¢/fl oz",
    5.64,
  ],
  [
    26,
    "Great Value Deli Style Sliced Sharp Cheddar Cheese, 8 oz, 12 Slices",
    "cheese",
    "Dairy",
    "sliced",
    "dairy",
    12,
    "8 oz",
    "24.6¢/oz",
    1.97,
  ],
  [
    27,
    "Great Value Milk 2% Reduced Fat Gallon Plastic Jug",
    "milk",
    "Dairy",
    "jug",
    "dairy",
    "",
    "gallon",
    "2.4¢/fl oz",
    3.12,
  ],
  [
    28,
    "Country Crock Calcium Buttery Spread, 45 oz Tub (Refrigerated)",
    "butter",
    "Dairy",
    "tub",
    "dairy",
    "",
    "45 oz",
    "13.2¢/oz",
    5.93,
  ],
  [
    29,
    "Great Value Finely Shredded Parmesan Cheese, 6 oz",
    "cheese",
    "Dairy",
    "shredded",
    "dairy",
    "",
    "6 oz",
    "32.8¢/oz",
    1.97,
  ],
  [
    30,
    "Hillshire Farm Ultra Thin Sliced Pastrami Deli Lunch Meat, 7 oz",
    "lunch meat",
    "Proteins",
    "sliced",
    "meat",
    "",
    "7 oz",
    "10.32/lb",
    4.54,
  ],
  [
    31,
    "Hillshire Farm Uncured Ultra Thin Hard Salami Deli Lunch Meat, 7 oz",
    "lunch meat",
    "Proteins",
    "sliced",
    "meat",
    "",
    "7 oz",
    "10.32/lb",
    4.54,
  ],
  [
    32,
    "Fresh Cosmic Crisp Apples, Each",
    "apples",
    "Frutes/Vege.",
    "fresh",
    "produce",
    "",
    "",
    "1.48/lb",
    1.01,
  ],
  [
    33,
    "Green Giant Fresh Washed & Trimmed Green Leaf Lettuce, 7 oz",
    "lettuce",
    "Frutes/Vege.",
    "fresh",
    "produce",
    "",
    "7 oz",
    "42.4¢/oz",
    2.97,
  ],
  [
    34,
    "Fresh Banana Fruit, Each",
    "banana",
    "Frutes/Vege.",
    "fresh",
    "produce",
    "",
    "",
    "58¢/lb",
    0.27,
  ],
  [
    35,
    "Marketside Caesar Chopped Salad Kit, 8.8 oz Bag, Fresh",
    "salad",
    "Frutes/Vege.",
    "kit",
    "produce",
    "",
    "8.8 oz",
    "45.2¢/oz",
    3.98,
  ],
  [
    36,
    "Fresh Roma Tomato, Each",
    "tomato",
    "Frutes/Vege.",
    "fresh",
    "produce",
    "",
    "",
    "98¢/lb",
    0.21,
  ],
  [
    37,
    "Fresh Green Leaf Lettuce, Each",
    "lettuce",
    "Frutes/Vege.",
    "fresh",
    "produce",
    "",
    "",
    "2.14/ea",
    2.14,
  ],
  [
    38,
    "De Wafelbakkers Chocolate Chip Pancakes, 33 oz, 24 Count Bag (Frozen)",
    "pancakes",
    "Grains",
    "bag",
    "frozen",
    "",
    "33 oz",
    "13.4¢/oz",
    4.42,
  ],
  [
    39,
    "Great Value Deli Style Wedges Seasoned Potatoes, 32 oz Bag (Frozen)",
    "potatoes",
    "Frutes/Vege.",
    "wedges",
    "frozen",
    "",
    "32 oz",
    "8.8¢/oz",
    2.82,
  ],
  [
    40,
    "Great Value Patties & Shredded Seasoned Potato Hash Brown",
    "potatoes",
    "Frutes/Vege.",
    "hash",
    "frozen",
    "",
    "",
    "",
    "2.97",
  ],
  [
    41,
    "Great Value Frozen Whole Kernel Corn, 32 oz Steamable Bag",
    "corn",
    "Frutes/Vege.",
    "bag",
    "frozen",
    "",
    "32 oz",
    "7.8¢/oz",
    2.48,
  ],
  [
    42,
    "De Wafelbakkers Buttermilk Pancakes, 33 oz, 24 Count Bag (Frozen)",
    "pancakes",
    "Grains",
    "bag",
    "frozen",
    "",
    "33 oz",
    "13.4¢/oz",
    4.42,
  ],
  [
    43,
    "Great Value Frozen 10oz Chopped Onions",
    "onions",
    "Frutes/Vege.",
    "chopped",
    "frozen",
    "",
    "10 oz",
    "14.6¢/oz",
    1.46,
  ],
  [
    44,
    "Great Value Seasoned French Fried Potatoes, 32 oz Bag (Frozen)",
    "potatoes",
    "Frutes/Vege.",
    "french fries",
    "frozen",
    "",
    "32 oz",
    "8.8¢/oz",
    2.82,
  ],
  [
    45,
    "Great Value Family Size Cheese Ravioli, Pasta, 48 oz Bag (Frozen)",
    "ravioli",
    "Grains",
    "bag",
    "frozen",
    "",
    "48 oz",
    "14.1¢/oz",
    6.77,
  ],
  [
    46,
    "Great Value Steak Cut French Fried Potatoes, 28 oz Bag (Frozen)",
    "potatoes",
    "Frutes/Vege.",
    "steak cut",
    "frozen",
    "",
    "28 oz",
    "10.1¢/oz",
    2.82,
  ],
  [
    47,
    "Great Value Thin Cut French Fried Potatoes, 26 oz Bag (Frozen)",
    "potatoes",
    "Frutes/Vege.",
    "thin cut",
    "frozen",
    "",
    "26 oz",
    "10.8¢/oz",
    2.82,
  ],
  [
    48,
    "Great Value All Natural Boneless Skinless Chicken Breasts, 5 lb (Frozen)",
    "chicken",
    "Proteins",
    "breasts",
    "frozen",
    "",
    "5 lb",
    "2.79/lb",
    13.94,
  ],
  [
    49,
    "Great Value Fully Cooked Original Pork Sausage Patties, Family Size, 35.6 oz (Frozen)",
    "sausage",
    "Proteins",
    "patties",
    "frozen",
    "",
    "35.6 oz",
    "4.45/lb",
    9.92,
  ],
  [
    50,
    "Equate 70% Isopropyl Alcohol Liquid, 16 fl oz",
    "alcohol",
    "Others",
    "liquid",
    "pharmacy",
    "",
    "16 fl oz",
    "2.08",
    9.92,
  ],
  [
    51,
    "Marketside Organic Grass-Fed Ground Beef, 85% Lean/15% Fat, 1 lb, 3 Count",
    "beef",
    "Proteins",
    "ground",
    "meat",
    3,
    "1 lb",
    "5.83/lb",
    17.48,
  ],
  [
    52,
    "Stove Top Cornbread Stuffing Mix Side Dish, 6 oz Box",
    "stuffing mix",
    "Grains",
    "box",
    "dry goods",
    "",
    "6 oz",
    "41.3¢/oz",
    2.48,
  ],
  [
    53,
    "Prego Homestyle Alfredo Pasta Sauce, 14.5 oz Jar",
    "pasta sauce",
    "Others",
    "jar",
    "canned goods",
    "",
    "14.5 oz",
    "17.1¢/oz",
    2.48,
  ],
  [
    54,
    "Del Monte Cut Green Beans Canned Vegetables, 14.5 oz Can",
    "green beans",
    "Frutes/Vege.",
    "can",
    "canned goods",
    "",
    "14.5 oz",
    "10.2¢/oz",
    1.48,
  ],
  [
    55,
    "Great Value Three Cheese Potatoes, 5 oz",
    "potatoes",
    "Frutes/Vege.",
    "frozen",
    "frozen goods",
    "",
    "5 oz",
    "25.2¢/oz",
    1.26,
  ],
  [
    56,
    "Barilla Classic Non-GMO, Kosher Certified Rotini Pasta, 16 oz",
    "pasta",
    "Grains",
    "box",
    "dry goods",
    "",
    "16 oz",
    "11.5¢/oz",
    1.84,
  ],
  [
    57,
    "Sweet Baby Ray's Honey BBQ 18 oz",
    "bbq sauce",
    "Others",
    "bottle",
    "condiments",
    "",
    "18 oz",
    "12.7¢/oz",
    2.28,
  ],
  [
    58,
    "Kraft Velveeta Original Shells & Cheese Dinner, 3 - 12 oz Boxes",
    "mac and cheese",
    "Grains",
    "box",
    "dry goods",
    3,
    "12 oz",
    "20.8¢/oz",
    7.47,
  ],
  [
    59,
    "Great Value Alfredo Pasta Sauce, 16 Oz",
    "pasta sauce",
    "Others",
    "jar",
    "canned goods",
    "",
    "16 oz",
    "11.4¢/oz",
    1.82,
  ],
  [
    60,
    "Great Value Fettuccine, 16 oz",
    "pasta",
    "Grains",
    "box",
    "dry goods",
    "",
    "16 oz",
    "6.1¢/oz",
    0.98,
  ],
  [
    61,
    "Great Value Long Grain Enriched Rice, 32 oz",
    "rice",
    "Grains",
    "bag",
    "dry goods",
    "",
    "32 oz",
    "5.5¢/oz",
    1.77,
  ],
  [
    62,
    "Prego Pasta Sauce, Italian Tomato Sauce with Roasted Garlic & Herbs, 24 oz Jar",
    "pasta sauce",
    "Others",
    "jar",
    "canned goods",
    "",
    "24 oz",
    "10.3¢/oz",
    2.48,
  ],
  [
    63,
    "Great Value Rotini, 16 oz Box, (Shelf Stable)",
    "pasta",
    "Grains",
    "box",
    "dry goods",
    "",
    "16 oz",
    "6.1¢/oz",
    0.98,
  ],
  [
    64,
    "Marketside Organic Grass-Fed Ground Beef, 93% Lean/ 7% Fat, 1 lb, 3 Count",
    "beef",
    "Proteins",
    "ground",
    "meat",
    3,
    "1 lb",
    "6.49/lb",
    19.47,
  ],
  [
    65,
    "Marketside Bacon Ranch Crunch Chopped Fresh Salad Kit, 9.76 oz Bag, Fresh",
    "salad",
    "Frutes/Vege.",
    "kit",
    "produce",
    "",
    "9.76 oz",
    "40.6¢/oz",
    3.98,
  ],
  [
    66,
    "Eggo Homestyle Original Waffles, Frozen Breakfast, 12.3 oz, 10 Count, Regular",
    "waffles",
    "Grains",
    "box",
    "frozen",
    "",
    "12.3 oz",
    "24.1¢/oz",
    2.97,
  ],
  [
    67,
    "Great Value Italian Style Meatballs, Family Size, 80 oz (Frozen)",
    "meatballs",
    "Proteins",
    "bag",
    "frozen",
    "",
    "80 oz",
    "20¢/oz",
    15.96,
  ],
  [
    68,
    "Great Value Chocolate Chip Cookies, Family Size, 18 oz",
    "cookies",
    "Others",
    "bag",
    "snacks",
    "",
    "18 oz",
    "18¢/oz",
    3.24,
  ],
  [
    69,
    "Hamburger Helper Pasta Beef with Rich Beef Flavor, 5.9 Ounces Box",
    "pasta",
    "Grains",
    "box",
    "dry goods",
    "",
    "5.9 oz",
    "25.1¢/oz",
    1.48,
  ],
  [
    70,
    "Hamburger Helper Pasta Four Cheese Lasagna, 5.5 Ounces Box",
    "pasta",
    "Grains",
    "box",
    "dry goods",
    "",
    "5.5 oz",
    "26.9¢/oz",
    1.48,
  ],
];
